# Changed publish directory for Github Pages
publishDir = "docs"

baseURL = "https://budujlegalnie.pl/"
languageCode = "en-us"
title = "Kancelaria Tomasz Świerniak"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Kancelaria Radcy Prawnego Tomasz Świerniak"
  description = "Kancelaria Radcy Prawnego Tomasz Świerniak posiada ponad 10-letnie doświadczenie w korporacyjnej obsłudze podmiotów gospodarczych. Jesteśmy jedną z nielicznych kancelarii działających na polskim rynku, nasi prawnicy posiadają specjalistyczną wiedzę z zakresu prawa budowlanego i deweloperskiego oraz doświadczenie w obsłudze podmiotów z branży budowlanej i deweloperskiej."

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Kancelaria"
    subtitle = "Radcy Prawnego Tomasz Świerniak"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Generalny Wykonawca"
      url = "budownictwo_generalny_wykonawca.html"

    [[params.navigation.links]]
      name = "Podwykonawca"
      url = "budownictwo_podwykonawca.html"

    [[params.navigation.links]]
      name = "Deweloper"
      url = "deweloperstwo_deweloper.html"
      
    [[params.navigation.links]]
      name = "Klient indywidualny"
      url = "deweloperstwo_klient_indywidualny.html"


    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Kontakt"
      url = "kontakt.html"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Buduj legalnie z nami"
    subtitle = "Kancelaria Radcy Prawnego Tomasz Świerniak posiada ponad 10-letnie doświadczenie w korporacyjnej obsłudze podmiotów gospodarczych."
    buttonText = "Usługi"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Generalny Wykonawca"
      subtitle = "Budownictwo"
      image = "Generalny_Wykonawca.jpg"
      url = "budownictwo_generalny_wykonawca.html"

    [[params.tiles.showcase]]
      title = "Podwykonawca"
      subtitle = "Budownictwo"
      image = "Podwykonawca.jpg"
      url = "budownictwo_podwykonawca.html"

    [[params.tiles.showcase]]
      title = "Deweloper"
      subtitle = "Deweloperstwo"
      image = "Deweloperka.jpg"
      url = "deweloperstwo_deweloper.html"

    [[params.tiles.showcase]]
      title = "Klient indywidualny"
      subtitle = "Deweloperstwo"
      image = "Klient_indywidualny.jpg"
      url = "deweloperstwo_klient_indywidualny.html"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "O Kancelarii"
    subtitle = """Kancelaria Radcy Prawnego Tomasz Świerniak posiada ponad 10-letnie doświadczenie w korporacyjnej obsłudze podmiotów gospodarczych. Jesteśmy jedną z nielicznych kancelarii działających na polskim rynku, nasi prawnicy posiadają specjalistyczną wiedzę z zakresu prawa budowlanego i deweloperskiego oraz doświadczenie w obsłudze podmiotów z branży budowlanej i deweloperskiej."""

    subtitle2 = """Kancelaria powstała w odpowiedzi na rosnące zapotrzebowanie na specjalistyczne usługi prawne. Jako kancelaria butikowa oferujemy usługi w wybranych obszarach specjalizacji, wykorzystując doświadczenie zdobyte w trakcie wieloletniej pracy w jednej z największych grup budowlanych, co pozwala nam świadczyć usługi na najwyższym poziomie. Jednocześnie – wykorzystując doświadczenie biznesowe Partnerów Kancelarii – zapewniamy naszym Klientom pomoc prawną dostosowaną do ich indywidualnych potrzeb, uwzględniającą nie tylko obowiązujące regulacje, ale też specyfikę ich działalności oraz rynków, w ramach których funkcjonują."""


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Wyślij"
    buttonClear = "Wyczyść"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "tomasz.swierniak@gmail.com"

    [[params.contact.phone]]
    title = "Telefon"
    phone = "(+48) 669 406 329"

    [[params.contact.address]]
    title = "Adres"
    street = "ul. Piotrowicka 99a/2"
    city = "40–724 Katowice"
    country = "Polska"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Radca Prawny Tomasz Świerniak"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/tomasz-świerniak-117b0814b/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
